name: 3D Profile
on:
  schedule:
    - cron: "0 1 * * *"  # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Generate SVGs (this action expects token in ENV)
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: ${{ github.repository_owner }}

      # 3) Commit generated files into profile-3d-contrib/
      - name: Commit & push 3D svgs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update 3D profile" || echo "No changes to commit"
          git push
