name: 3D Profile
on:
  schedule:
    - cron: "0 1 * * *"  # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Generate SVGs (token passed as INPUT, not env)
      - name: Generate 3D contributions
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}

      # 3) Ensure folder exists (some runners need this)
      - name: Ensure output folder
        run: mkdir -p profile-3d-contrib

      # 4) Commit & push generated files
      - name: Commit & push 3D svgs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update 3D profile" || echo "No changes to commit"
          git push
