name: Snake
on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout first (we need a repo to commit into)
      - uses: actions/checkout@v4

      # 2) Generate the SVGs (light + dark)
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      # 3) Commit the generated files
      - name: Push snake animation
        run: |
          mkdir -p output
          cp dist/snake.svg output/github-contribution-grid-snake.svg
          cp dist/snake-dark.svg output/github-contribution-grid-snake-dark.svg || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/*.svg
          git commit -m "chore: update snake animation" || echo "No changes to commit"
          git push
